- CHANGELOG.md
- src/args/argument_list.go
- src/metrics/database_metric_definitions.go
- src/metrics/instance_metric_definitions.go
- src/metrics/metrics.go
- src/metrics/metrics_test.go
- src/mssql.go
Add `enable_buffer_metrics` option. Buffer metrics can be time intensive for large systems, and the metrics may not be that useful, so we should provide an option to disable them.
> Buffer space config

- CHANGELOG.md
- Makefile
- README.md
- mssql-definition.yml
- mssql-win-definition.yml
- pkg/windows/nri-amd64-installer/Product.wxs.template
- src/mssql.go
- win_build.ps1
- windows_set_version.ps1
- Renamed the integration executable from nr-mssql to nri-mssql in order to be consistent with the package naming. **Important Note:** if you have any security module rules (eg. SELinux), alerts or automation that depends on the name of this binary, these will have to be updated.
> Update executable prefix from nr- to nri-.

- mssql-config.yml.sample
- src/args/argument_list.go
- src/connection/sql_connection.go
- src/metrics/metrics.go
This commit adds support for a `custom_metrics_query` argument. The
argument must be a SQL query string that has the columns 'metric_name',
'metric_value', and 'metric_type'. Additional columns are not required,
but if they exist, they will be added to the metric set as attributes
where the column name is the attribute key and the value for that row is the
attribute value.
Add a detailed description and purpose of your changes.
Link the issue it solves (if there is one).
> Add custom metrics query argument

- README.md
- mssql-custom-query.yml.sample
- src/args/argument_list.go
- src/metrics/metrics.go
- src/mssql.go
- Added new command line option `-custom_metrics_config` for queries in YAML
- Included sample config `mssql-custom-query.yml.sample`
- Update `-custom_metrics_query` to auto-detect type
- Support for `exec procedure` with YAML queries
- Risk is only to custom queries command-line options
- Tested on several examples, it looks ok
> Update populateCustomMetrics() for queries in YAML, auto-detect metric type

- CHANGELOG.md
- src/instance/sql_instance.go
- src/instance/sql_instance_test.go
- src/mssql.go
MSSQL instances were being reported with only the host name instead of the full instance name
> fix: sql instance entity name was being reported incorrectly

- .github/workflows/prerelease.yml
[Current package](http://download.newrelic.com/infrastructure_agent/linux/apt/pool/main/n/nri-mssql/nri-mssql_0.1.5-1_amd64.deb) in repo is too old and has a different configfile specification for .deb. this causes that the installation test upgrade path prompts a message to replace the definition file and makes the test fail since that is not being handled.
The goal of This PR is to disable this test (upgrade path) for the first package. 
I have perfomed the test locally and if the prompt is answered the integrations upgrades successfully.
> fix: disable upgrade package test

- src/database/sql_database.go
- src/metrics/database_metric_definitions.go
updated the database list to include 2 system databases from mssql alwayson availability groups: model_msdb and model_replicatedmaster.
> mssql alwayson update

- CHANGELOG.md
- src/metrics/instance_metric_definitions.go
Avoids potential deadlocks when other queries are blocking this particular table (E.g.: conflicting RESTORE LOG).
> include "nolock" in total disk space query

- src/metrics/metrics.go
This PR fixes an issue with nextResultSet used to retrieve the presence of results from a custom query.
This had an unexpected effect of moving to the nextResultSet which prevented us to walk the records for the first result set returned causing custom queries to always return an empty set of records.
> fix resultSet bug in custom queries

- mssql-custom-query.yml.sample
Removed `[tab]` characters and replaced with normal space characters to fix the indents.  The `[tab]` characters indented some queries too much, causing the issues sending data back to New Relic.
> fix: removed indents breaking integration

- .github/renovate.json5
- .github/workflows/on_prerelease.yml
- .github/workflows/on_release.yml
- .github/workflows/push_pr.yml
- .github/workflows/security.yml
- .github/workflows/trigger_prerelease.yml
- .gitignore
- CHANGELOG.md
- Makefile
- build/Dockerfile
> NR-121907: use release toolkit

- build/ci.mk
It makes [Test binary compilation and packaging for linux](https://github.com/newrelic/nri-mssql/actions/runs/5801595470/job/15742702128?pr=129) fail due to missing signature credentials.
Package signature is not supposed to be tested there.
> fix: include misning env variable for testing packages build

- CHANGELOG.md
- src/metrics/instance_metric_definitions.go
- src/metrics/metrics.go
Fixes #153 
`int64` (instead of `int`) is used to represent numeric values coming from queries. [API limits](https://docs.newrelic.com/docs/data-apis/ingest-apis/metric-api/metric-api-limits-restricted-attributes/) are respected and `int64` is already used in other sdk-based integrations ([example](https://github.com/newrelic/nri-postgresql/blob/f6164ff87d18aaaa4e6c4044a3d7baf456a62e3b/src/metrics/table_definitions.go#L66))
> [NR-254437] fix: use int64 instead of int for numeric values from queries

- Makefile
- README.md
- tests/helper.go
`docker-compose` v1 is EOL, and we need to move to `docker compose` (wit a space).
> [NR-286408] chore: update docker compose command

- CHANGELOG.md
- Makefile
- go.mod
- src/metrics/metrics.go
- src/metrics/metrics_test.go
- src/testdata/customQuery.json
- src/testdata/customQueryPrefix.json
- tests/mssql_test.go
This PR updates the function handling custom queries in order that it can parse DECIMAL values.
The previous implementation was scanning all the values into `interface{}` values, which means that the driver performs no conversion, and later it was converting all the values to string, to finally try to convert to `Float64` for the corresponding types. This wasn't working well because the driver represents DECIMAL values as `uint8[]` and the corresponding conversion to string was an array of bytes. We have updated it to directly scan the values into the `string` type (which tells the driver to perform the corresponding conversion) and later, we keep converting the strings to numbers only when needed.
The PR also includes a small refactor of the function handling custom queries and some …
> [NR-302034] fix: handle DECIMAL values in custom queries

- CHANGELOG.md
- mssql-config.yml.sample
- src/args/argument_list.go
- src/metrics/instance_metric_definitions.go
- src/metrics/metrics.go
- src/metrics/metrics_test.go
Add `enable_disk_metrics_in_bytes` argument (default true), allows disabling disk-space-metrics
Docs PR https://github.com/newrelic/docs-website/pull/19312
> add argument to disable disk-space-metrics

- CHANGELOG.md
- src/metrics/metrics.go
- src/metrics/metrics_test.go
- src/testdata/customQueryNull.json
What this PR fixes: Report `MssqlCustomQuerySample` data if there is NULL value in the output of the `CUSTOM_METRICS_QUERY`.
Changes in this PR:
1. Using sql.NullString while scanning rows of the custom query output. If the custom query output has null values a check is added to verify and set it as empty string, proceed with scanning other rows instead of failing.
2. Added unit tests for the same.
Testing details can be found [here](https://new-relic.atlassian.net/browse/NR-365328?focusedCommentId=1141678)
> fix: handle null values while populating custom query metrics

- CHANGELOG.md
[Pre release](https://github.com/newrelic/nri-mssql/releases/tag/v2.17.1) broke mid [pipeline](https://github.com/newrelic/nri-mssql/actions/runs/13784792445/job/38550972442#step:3:473) so re releasing with a the tag 2.17.2
> Add changelog for v2.17.2

- src/queryanalysis/validation/sql_server_version.go
- src/queryanalysis/validation/sql_server_version_test.go
What it does ?
Added support for Microsoft SQL Azure (RTM) - 12.0.2000.8 in the nri-mssql. The current nri-mssql versions support standard SQL from major version numbers 14 to 16. This PR extends support to include versions 12 to 14 specifically for Azure SQL, with the Azure cloud currently using version 12. Support up to version 16 has been included for future compatibility."
Testing:
The test cases for Azure SQL version were executed with the scenarios listed below, and all tests passed successfully.
1) go test -v -run TestCheckSQLServerVersionforAzure
> NR-401130: Added version support of Azure SQL in nri-mssql.

- src/database/sql_database.go
- src/database/sql_database_test.go
This PR introduces two new functions:
- GetEngineEdition(connection *SQLConnection) (int, error): This function queries the database to retrieve the SQL Server engine edition. It handles the database interaction, including executing the query and processing the result.  If the query returns no rows, it logs a debug message and returns 0 without an error.
- IsAzureSQLDatabase(engineEdition int) bool: This function determines whether a given engine edition corresponds to Azure SQL Database.  It specifically checks if the engine edition is 5, which is the value for Azure SQL Database.
These functions provide a clear and consistent way to obtain and interpret the SQL Server engine edition, particularly in the context of differentiating between Azure SQL Database and other SQL Server …
> add funcs that identify azure sql database

- src/common/query_skip.go
- src/database/sql_database.go
- src/database/sql_database_test.go
- src/inventory/inventory.go
- src/inventory/inventory_test.go
- src/metrics/instance_metric_definitions.go
- src/metrics/metrics.go
- src/metrics/metrics_test.go
- src/mssql.go
- src/testdata/nonEmptyMetrics.json.golden
-  Skip Unsupported SQL Queries pattern (`sys.dm_os_process_memory`,`sys.master_files`,`exec sp_configure`,`sys.dm_os_sys_memory`,`sys.dm_os_volume_stats`) for Azure SQL Database 
```shell
test@1234 bin %./nri-mssql -username="**"  -password="**" -port=1433 -hostname="**" -enable_buffer_metrics=true -enable_database_reserve_metrics=true -enable_disk_metrics_in_bytes -verbose=true
06:16:12.725108 [DEBUG] store file (/tmp/nr-integrations/com.newrelic.mssql-620af03b7337b72def7d45b9e21132e3.json) is older than 6m0s, skipping loading from disk.
[DEBUG] Running query: select COALESCE( @@SERVERNAME, SERVERPROPERTY('ServerName'), SERVERPROPERTY('MachineName')) as instance_name
[DEBUG] Running query: SELECT SERVERPROPERTY('EngineEdition') AS EngineEdition;
[DEBUG] Skipping query 'EXEC …
```
> NR-408418: remove Unsupported SQL Queries for Azure SQL Database

- src/connection/sql_connection.go
- src/connection/sql_connection_test.go
- src/metrics/database_metric_definitions.go
- src/metrics/metrics.go
- src/metrics/metrics_test.go
- src/mssql.go
- src/testdata/azureSQLDatabaseMetrics.json.golden
- src/testdata/partialAzureSQLDatabaseMetrics.json.golden
Changes in this PR - 
When instrumenting an Azure SQL Database type service.
- Populate database metrics using queries that are specific to Azure SQL Database.
- Create new connections to each database for retrieving database metrics.
- Add unit tests for the same.
Below are the list of database metrics that are retrieved using Azure SQL Database specific queries.
1. `log.transactionGrowth`
2. `io.stallInMilliseconds`
3. `bufferpool.sizePerDatabaseInBytes`
4. `pageFileTotal`
5. `pageFileAvailable`
<details><summary>Testing Details : </summary>
<p>
```shell
root@sairaj-mssql-test-2:/home/sairaj/nri-mssql/bin# ./nri-mssql -username="newrelic"  -password="*****" -port=1433 -hostname="test.database.windows.net" -enable_buffer_metrics=true -enable_database_reserve_metrics=true …
```
> feat: create new connections to each database in case of azure sql database

- spec.csv
- src/inventory/inventory.go
- src/inventory/inventory_test.go
- src/metrics/database_metric_definitions.go
- src/metrics/metrics.go
- src/metrics/metrics_test.go
- src/testdata/azureSQLDatabaseMetricsWithoutMemoryMetrics.json.golden
- src/testdata/databasePartialMemoryMetrics.json.golden
- src/testdata/partialAzureSQLDatabaseMetrics.json.golden
- Add new queries to populate `memoryUtilization`, `memoryTotal`, `memoryAvailable`, `maxDiskSizeInBytes` for azure sql database.
- Add logic to execute queries and populate the above mentioned metrics per database when instrumenting an azure sql database i.e the metrics should come under MssqlDatabaseSample
- Added unit tests for the same.
Docs update - https://github.com/newrelic/docs-website/pull/20674
<details><summary> Testing Details: </summary>
<p>
```shell
root@sairaj-mssql-test-2:/home/sairaj/nri-mssql/bin# ./nri-mssql -username="newrelic"  -password="***" -port=1433 -hostname="test.database.windows.net" -enable_buffer_metrics=true -enable_database_reserve_metrics=true -enable_disk_metrics_in_bytes -verbose=true
09:29:30.001434 [DEBUG] store file …
```
> feat: populate memory, disk metrics and inventory for azure sql database

- CHANGELOG.md
- spec.csv
- src/common/query_skip.go
- src/connection/sql_connection.go
- src/connection/sql_connection_test.go
- src/database/sql_database.go
- src/database/sql_database_test.go
- src/inventory/inventory.go
- src/inventory/inventory_test.go
- src/metrics/database_metric_definitions.go
- src/metrics/database_metric_definitions_test.go
- src/metrics/instance_metric_definitions.go
- src/metrics/metrics.go
- src/metrics/metrics_test.go
- src/mssql.go
- src/testdata/azureSQLDatabaseMetrics.json.golden
- src/testdata/azureSQLDatabaseMetricsWithoutMemoryMetrics.json.golden
- src/testdata/databasePartialMemoryMetrics.json.golden
- src/testdata/nonEmptyMetrics.json.golden
- src/testdata/partialAzureSQLDatabaseMetrics.json.golden
- Add regular monitoring support for azure sql database
High level changes in this PR
- Add functions that Identify the server being monitored as an azure sql database (#222)
- Skip running unsupported sql queries for azure sql database (#226)
- Add new database definition queries for azure sql database (#227)
- Create new connections to each database in case of azure sql database (#228)
- Populate memory, disk metrics and inventory for azure sql database (#229)
Docs [forked repo PR](https://github.com/sairaj18/docs-website/pull/1) to support Azure SQL Database. These changes will be commited to the original docs-website repo as part of this [PR](https://github.com/newrelic/docs-website/pull/20674)
Did a manual install of `nri-mssql` integration on an Azure Windows VM and replaced the …
> feat: Add regular monitoring support for azure sql database

- CHANGELOG.md
- src/queryanalysis/config/query_config.go
This PR corrects a critical time zone issue where MSSQLTopSlowQueries and ExecutionPlanQuery were using GETUTCDATE() to filter against qs.last_execution_time, which is stored in server local time. The mismatch caused queries to return no recent data in environments where local time is ahead of UTC.
Replace GETUTCDATE() with SYSDATETIME() in both query time filters to align with the sys.dm_exec_query_stats DMV's local time storage
Integration tests running against SQL Server instances in different time zones will validate that recent slow queries and execution plans are now properly collected within the specified interval window. No additional tests are needed IMO.
> Converted GETUTCDATETIME() to SYSDATETIME()
